# 如何排查数据集成问题 {#concept_bnt_kkb_r2b .concept}

当通过数据集成实现某操作出现问题时，首先要定位问题的相关信息。例如查看运行资源、数据源信息，确认配置任务的区域等。

## 查看运行资源 {#section_las_hvq_v7m .section}

-   任务运行在默认的资源组上，日志中会出现如下信息：

    ``` {#codeblock_gt5_9wp_tl3}
    running in Pipeline[basecommon_ group_xxxxxxxxx]
    ```

-   任务运行在数据集成自定义资源组上，日志中会出现如下信息：

    ``` {#codeblock_ww4_4kt_4cg}
    running in Pipeline[basecommon_xxxxxxxxx]
    ```

-   任务运行在独享数据集成资源上，日志中会出现如下信息：

    ``` {#codeblock_u56_bfi_vc8}
    running in Pipeline[basecommon_S_res_group_xxx]
    ```


## 查看数据源信息 {#section_v3x_shb_r2b .section}

需要查看的数据源的相关信息如下：

1.  确认是什么数据源之间的同步。
2.  确认是什么环境的数据源。

    阿里云数据库、连接串模式（数据集成网络可直接连通）、连接串模式（数据集成网络不可直接连通）、VPC网络环境的数据源（RDS或其它数据源）、金融云环境（VPC环境、经典网络）。

3.  确认数据源测试连通性是否成功。

    请参见[配置数据源](intl.zh-CN/使用指南/数据集成/数据源配置/支持的数据源.md#)文档，确认数据源的相关信息是否正确。通常填错的情况如下：

    -   多个数据源库填错。
    -   填写的信息中加了空格或特殊字符。
    -   不支持测试连通性的问题，例如连接串模式（数据集成网络不可直接连通）的数据源、除RDS的VPC环境的数据源。

## 确认配置任务的区域 {#section_dfl_snb_r2b .section}

进入DataWorks控制台，可以查看相关的区域，例如华东2、华南1、中国（香港）、亚太东南1、欧洲中部1、亚太东南2等，通常默认是华东2。

**说明：** 购买MaxCompute后，方可查看相应的区域。

![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15669884468678_zh-CN.png)

## 界面模式报错，复制排查码 {#section_n3w_ynb_r2b .section}

如果报错，请复制排查码，并提供给处理人员。

![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15669884468679_zh-CN.jpg)

## 解读日志报错 {#section_i2l_g4b_r2b .section}

-   日志中报SQL语句执行失败（列包含关键字）。

    ``` {#codeblock_vos_s12_925}
    2017-05-31 14:15:20.282 [33881049-0-0-reader] ERROR ReaderRunner - Reader runner Received Exceptions:com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-07]
    ```

    错误解读：

    读取数据库数据失败，请检查您配置的column/table/where/querySql或者向数据库管理员寻求帮助。

    执行的SQL如下所示：

    ``` {#codeblock_cmq_1je_ztw}
    select **index**,plaid,plarm,fget,fot,havm,coer,ines,oumes from xxx
    ```

    错误信息如下所示：

    ``` {#codeblock_8w0_gyc_2l8}
    You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near **index**,plaid,plarm,fget,fot,havm,coer,ines,oumes from xxx
    ```

    排查思路：

    1.  本地运行SQL语句`select **index**,plaid,plarm,fget,fot,havm,coer,ines,oumes from xxx`，查看其结果，通常也会有相应的报错。
    2.  字段中有关键字index，解决方法加单引号或修改字段。
-   日志中报SQL语句执行失败（表名带有双引号包单引号）。

    ``` {#codeblock_b2b_ibh_ccp}
    com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-07]
    ```

    错误解读：

    读取数据库数据失败，请检查您配置的column/table/where/querySql或者向数据库管理员寻求帮助。

    执行的SQL如下所示：

    ``` {#codeblock_9ee_xex_w9l}
    select /_+read_consistency(weak) query_timeout(100000000)_/ _ from** 'ql_ddddd_[0-31]’ **where 1=2
    ```

    错误信息如下所示：

    ``` {#codeblock_yfm_onj_hlg}
    You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘‘ql_live_speaks[0-31]’ where 1=2’ at line 1 - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near **’‘ql_ddddd_[0-31]’ where 1=2’ **
    ```

    排查思路：

    配置表名时，需要双引号包单引号。通常配置常量是双引号包单引号，例如`“table”:[“‘qlddddd[0-31]’”]`，直接去掉里面的单引号。

-   测试数据源连通性失败（Access denied for）。

    连接数据库失败，数据库连接串：`jdbc:mysql://xx.xx.xx.x:3306/t_demo`，用户名：fn\_test， 异常消息：`Access denied for user ‘fn_test’@’%’ to database ‘t_demo’`，请确定RDS中已经添加白名单。

    排查思路：

    -   通常出现Access denied for异常，是因为填写的信息有问题，请确认您填写的信息。
    -   白名单或者用户的账号有没有对应数据库的权限，RDS管控台可以添加相应的白名单和授权。
-   路由策略有问题，运行的池子oxs和ECS集群。

    ``` {#codeblock_p4g_p3h_zgh}
    2017-08-08 15:58:55 : Start Job[xxxxxxx], traceId **running in Pipeline[basecommon_group_xxx_cdp_oxs]**ErrorMessage:Code:[DBUtilErrorCode-10]
    ```

    错误解读：

    连接数据库失败，请检查您的账号、密码、数据库名称、IP、Port或者向数据库管理员寻求帮助（注意网络环境）。数据库连接失败，因为根据您配置的连接信息，无法从jdbc:oracle:thin:@xxx.xxxxx.x.xx:xxxx:prod中找到可连接的JDBCUrl，请检查您的配置并进行修改。

-   ava.lang.Exception：DataX无法连接对应的数据库。

    错误解读：

    出现该错误可能的原因如下：

    -   配置的ip/port/database/jdbc错误，无法连接。
    -   配置的username/password错误，鉴权失败。请和数据库管理员确认该数据库的连接信息是否正确。
    排查思路：

    情况一：

    -   Oracle同步的RDS-PostgreSQL直接单击**运行**，不能在调度中运行，因为运行的池子不同。
    -   添加RDS的数据源时，改成添加普通JDBC形式的数据源，则Oracle同步的RDS-PostgreSQL可以在调度中运行。
    情况二：

    -   VPC环境的RDS-PostgreSQL不能运行在自定义资源组上，因为VPC环境的RDS有反向代理功能，这样与用户自定义资源组存在网络问题。因此，通常VPC环境的RDS直接运行在DataWorks默认的资源即可。如果默认资源不能满足您的需要，要运行在自己的资源上，可以将VPC环境的RDS作为VPC环境JDBC形式的数据源，购买一个同网段的ECS。
    -   通常VPC环境的RDS映射出的URL为`jdbc:mysql://100.100.70.1:4309/xxx`，100开头的IP是后台映射出来的，如果是一个域名的表现形式则为非VPC环境。
-   HBase Writer不支持DATE类型。

    ``` {#codeblock_cw0_23f_0bs}
    HBase同步到hbase:2017-08-15 11:19:29 : State: 4(FAIL) | Total: 0R 0B | Speed: 0R/s 0B/s | Error: 0R 0B | Stage: 0.0% ErrorMessage:Code:[Hbasewriter-01]
    ```

    错误解读：

    您填写的参数值不合法。

    Hbasewriter不支持DATE类型，目前支持的类型包括STRING、BOOLEAN、SHORT、INT、LONG、FLOAT和DOUBLE。

    排查思路：

    -   HBase的Writer不支持DATE类型，所以在Writer中不能配置DATE类型。
    -   直接配置STRING类型，因为HBase没有数据类型的概念，底层通常是BYTE数组。
-   JSON格式配置错误。

    column配置错误。

    经DataX智能分析，该任务最可能的错误原因如下：

    ``` {#codeblock_o5q_n76_hsy}
    com.alibaba.datax.common.exception.DataXException: Code:[Framework-02]
    ```

    错误解读：

    DataX引擎运行过程出错，详情请参见DataX运行结束时的错误诊断信息。

    java.lang.ClassCastException：com.alibaba.fastjson。JSONObject cannot be cast to java.lang.String

    排查思路：

    发现其JSON配置有问题。

    ``` {#codeblock_0h6_17p_k9b}
    writer端： 
    “column”:[ 
    { 
    “name”:“busino”, 
    “type”:“string” 
    } 
    ] 
    正确的写法： 
    “column”:[ 
    { 
    “busino” 
    } 
    ]
    ```

-   JSON List编写缺少\[\]。

    经DataX智能分析，该任务最可能的错误原因如下所示：

    ``` {#codeblock_3m7_f6n_o2o}
    com.alibaba.datax.common.exception.DataXException: Code:[Framework-02]
    ```

    错误解读：

    DataX引擎运行过程出错，详情请参见DataX运行结束时的错误诊断信息。

    ``` {#codeblock_l1q_9m5_2m2}
    java.lang.String cannot be cast to java.util.List - java.lang.String cannot be cast to java.util.List  
    at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41)
    ```

    排查思路：

    少了\[\]，list型变成其他的形式，找到对应的地方填上\[\]即可解决问题。

-   权限问题
    -   缺少delete权限。

        MaxCompute同步到RDS-MySQL，报错如下：

        ``` {#codeblock_tox_lxn_l7s}
        ErrorMessage:Code:[DBUtilErrorCode-07]
        ```

        错误解读：

        读取数据库数据失败，请检查您配置的column/table/where/querySql或者向数据库管理员寻求帮助。

        执行的SQL如下所示：

        ``` {#codeblock_8uy_h9b_9g2}
        delete from fact_xxx_d where sy_date=20170903
        ```

        具体错误信息如下所示：

        ``` {#codeblock_0g3_5fj_o0d}
        **DELETE command denied** to user ‘xxx_odps’@‘[xx.xxx.xxx.xxx](http://xx.xxx.xxx.xxx)’ for table ‘fact_xxx_d’ - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: DELETE command denied to user ‘xxx_odps’@‘[xx.xxx.xxx.xxx](http://xx.xxx.xxx.xxx)’ for table 'fact_xxx_d’
        ```

        排查思路：

        DELETE command denied to没有删除此表的权限，到相应的数据库设置相关表的删除权限。

    -   缺少drop权限。

        ``` {#codeblock_ngz_vj7_x6v}
        Code:[DBUtilErrorCode-07]
        ```

        错误解读：

        读取数据库数据失败，请检查您配置的column/table/where/querySql或者向数据库管理员寻求帮助。

        执行的SQL为`truncate table be_xx_ch`

        具体错误信息如下所示：

        ``` {#codeblock_d8k_gav_nnw}
        **DROP command denied to user** ‘xxx’@‘[xxx.xx.xxx.xxx](http://xxx.xx.xxx.xxx)’ for table ‘be_xx_ch’ - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: DROP command denied to user ‘xxx’@‘[xxx.xx.xxx.xxx](http://xxx.xx.xxx.xxx)’ for table 'be_xx_ch’
        ```

        排查思路：

        MySQL Writer配置执行前准备语句truncate删除表中的数据报上面错误，是因为没有drop的权限。

-   ADS权限问题。

    ``` {#codeblock_ek3_89a_xjf}
    2016-11-04 19:49:11.504 [job-12485292] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://100.98.249.103:3306/ads_rdb?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true.  
    2016-11-04 19:49:11.505 [job-12485292] WARN  OriginalConfPretreatmentUtil
    ```

    您的配置文件中的列配置存在一定的风险，因为您未配置读取数据库表的列，当您的表字段个数、类型有变动时，可能影响任务正确性甚至会运行出错。请检查您的配置并进行修改。

    ``` {#codeblock_iou_ukk_934}
    2016-11-04 19:49:11.528 [job-12485292] INFO Writer$Job
    ```

    如果是MaxCompute\>ADS的数据同步，需要完成以下两方面的授权。

    -   ADS官方账号至少需要有需要同步的表的describe和select权限，因为ADS系统需要获取MaxCompute需要同步表的结构和数据信息。
    -   您配置的ADS数据源访问账号AK，需要拥有向指定的ADS数据库发起load data的权限，您可以在ADS系统中添加授权。
    ``` {#codeblock_amv_ay9_0fe}
    2016-11-04 19:49:11.528 [job-12485292] INFO Writer$Job
    ```

    如果是RDS（或其他非MaxCompute数据源）\>ADS的数据同步，实现逻辑为先将数据装载到MaxCompute临时表，再从MaxCompute临时表同步至ADS，中转MaxCompute项目为cdp\_ads\_project，中转项目账号为cloud-data-pipeline@aliyun-inner.com。

    权限方面：

    -   ADS官方账号至少需要有需要同步的表（这里指MaxCompute临时表）的describe和select权限，因为ADS系统需要获取MaxCompute需要同步的表的结构和数据信息，此部分部署时已经完成授权。
    -   中转MaxCompute对应的账号cloud-data-pipeline@aliyun-inner.com，要拥有向指定的ADS数据库发起load data的权限，您可以在ADS系统中添加授权。
    排查思路：

    出现此问题是因为没有设置load data权限。

    中转项目账号为cloud-data-pipeline@aliyun-inner.com，权限方面：ADS官方账号至少需要拥有需要同步的表（这里指 MaxCompute 临时表）的 describe 和 select 权限，因为ADS系统需要获取MaxCompute需要同步的表的结构和数据信息，此部分部署时已经完成授权，登录ADS管控台给ADS授予load data的权限。

-   白名单问题
    -   没有添加白名单导致测试连通性失败。

        测试连接失败，测试数据源连通性失败：

        ``` {#codeblock_afl_ucd_f8a}
        error message: **Timed out after 5000** ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{[address:3717=dds-bp1afbf47fc7e8e41.mongodb.rds.aliyuncs.com](http://address:3717=dds-bp1afbf47fc7e8e41.mongodb.rds.aliyuncs.com), type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {[address:3717=dds-bp1afbf47fc7e8e42.mongodb.rds.aliyuncs.com](http://address:3717=dds-bp1afbf47fc7e8e42.mongodb.rds.aliyuncs.com), type=UNKNOWN, state=CONNECTING,** exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream**}}]
        ```

        排查思路

        非VPC环境的MongoDB，添加数据源时报Timed out after 5000，白名单添加有问题。

        **说明：** 如果您使用的是云数据库MongoDB版，MongoDB默认会有root账号。出于安全策略的考虑，数据集成仅支持使用MongoDB数据库对应账号进行连接，您添加使用MongoDB数据源时，也请避免使用root作为访问账号。

    -   白名单不全。

        ``` {#codeblock_0vq_bxn_tvg}
        for Code:[DBUtilErrorCode-10]
        ```

        错误解读：

        连接数据库失败，请检查您的账号、密码、数据库名称、IP、Port或者向数据库管理员寻求帮助（注意网络环境）。

        错误信息如下所示：

        ``` {#codeblock_ha2_pkr_tx6}
        java.sql.SQLException: Invalid authorization specification,  message from server: "#**28000ip not in whitelist, client ip is xx.xx.xx.xx".**  
        2017-10-17 11:03:00.673 [job-xxxx] ERROR RetryUtil - Exception when calling callable
        ```

        排查思路：

        白名单没有添全，没有将用户自己的资源添加白名单内。

-   数据源信息填写错误。
    -   脚本模式配置缺少相应数据源信息（could not be blank）。

        ``` {#codeblock_l45_1d3_uwu}
        2017-09-06 12:47:05 [INFO] Success to fetch meta data for table with **projectId [43501]** **项目ID **and instanceId **[mongodb]数据源名.**  
        2017-09-06 12:47:05 [INFO] Data transport tunnel is CDP.  
        2017-09-06 12:47:05 [INFO] Begin to fetch alisa account info for 3DES encrypt with parameter account: [zz_683cdbcefba143b7b709067b362d4385].  
        2017-09-06 12:47:05 [INFO] Begin to fetch alisa account info for 3DES encrypt with parameter account: [zz_683cdbcefba143b7b709067b362d4385].  
        [Error] Exception when running task, message:** Configuration property [accessId]通常是odps数据源要填写的信息 could not be blank!**
        ```

        排查思路：

        报错显示没有相应的accessId信息，通常出现这种现象是脚本模式，查看用户配置的JSON代码，是否忘记写相应的数据源名。

    -   数据源配置错误或未配置数据源。

        ``` {#codeblock_0ce_uon_5h4}
        2017-10-10 10:30:08 INFO =================================================== 
        File “/home/admin/synccenter/src/Validate.py”, line 16, in notNone 
        raise Exception(“Configuration property [%s] could not be blank!” % (context)) 
        **Exception: Configuration property [username] could not be blank!**
        ```

        排查思路：

        -   根据正常打出的日志进行对比：

            ``` {#codeblock_zc6_nzf_jr7}
            [56810] and instanceId(instanceName) [spfee_test_mysql]… 
            2017-10-09 21:09:44 [INFO] Success to fetch meta data for table with projectId [56810] and instanceId [spfee_test_mysql].
            ```

        -   由rds-mysql显示的信息可见，调数据源失败且报用户为空，说明数据源的位置配置错误或未配置数据源。
    -   DRDS连接数据超时。

        MaxCompute同步数据到DRDS，经常出现下面的错误：

        ``` {#codeblock_o4f_ayd_bas}
        [2017-09-11 16:17:01.729 [49892464-0-0-writer] WARN CommonRdbmsWriter$Task
        ```

        回滚此次写入，采用每次写入一行方式提交，原因如下：

        ``` {#codeblock_5by_pc3_4b3}
        com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: **Communications link failure  **  
        The last packet successfully received from the server was 529 milliseconds ago.  The last packet sent successfully to the server was** 528 milliseconds ago**.
        ```

        ![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15669884468686_zh-CN.png)

        排查思路：

        DataX客户端的超时。您可以在添加DRDS数据源时加上`?useUnicode=true&characterEncoding=utf-8&socketTimeout=3600000`超时参数。

        示例如下：

        ``` {#codeblock_y11_q93_hsp}
        jdbc:mysql://10.183.80.46:3307/ae_coupon?useUnicode=true&characterEncoding=utf-8&socketTimeout=3600000
        ```

    -   系统内部错误。

        排查思路：

        通常是在开发环境改错了JSON格式并直接保存，导致报错位系统内部问题。界面显示为空白，碰到该问题，直接提供您的工作空间名称和节点名称进行咨询。

-   脏数据
    -   脏数据（String\[“”\]不能转为Long）。

        ``` {#codeblock_lu7_t7n_d0a}
        2017-09-21 16:25:46.125 [51659198-0-26-writer] ERROR WriterRunner - Writer Runner Received Exceptions:  
        com.alibaba.datax.common.exception.DataXException: Code:[Common-01]
        ```

        错误解读：

        同步数据出现业务脏数据情况，数据类型转换错误。String\[“”\]不能转为Long。

        排查思路：

        String\[“”\]不能转为Long：两张表格中的建表语句一样，报上述错误是因为字段类型中的空字段不能转换成Long类型，直接配置成String类型。

    -   脏数据（Out of range value）。

        ``` {#codeblock_zry_egm_xme}
        2017-11-07 13:58:33.897 [503-0-0-writer] ERROR StdoutPluginCollector 
        脏数据： 
        {“exception”:“Data truncation: Out of range value for column ‘id’ at row 1”,“record”:[{“byteSize”:2,“index”:0,“rawData”:-3,“type”:“LONG”},{“byteSize”:2,“index”:1,“rawData”:-2,“type”:“LONG”},{“byteSize”:2,“index”:2,“rawData”:“其他”,“type”:“STRING”},{“byteSize”:2,“index”:3,“rawData”:“其他”,“type”:“STRING”}],“type”:“writer”}
        ```

        排查思路：

        mysql2mysql，源端设置的是smallint\(5\)，目标端是int\(11\) unsigned，因为smallint\(5\)范围有负数，unsigned不允许有负数，所以产生脏数据。

    -   脏数据（存储emoji）。

        数据表配置成了可以存储emoji的，同步时报脏数据。

        排查思路：

        同步emoji时报错脏数据，需要修改编码格式：

        -   JDBC形式添加数据源

            ``` {#codeblock_3ry_ntj_w7n}
            jdbc:mysql://xxx.x.x.x:3306/database?characterEncoding=utf8&com.mysql.jdbc.faultInjection.serverCharsetIndex=45
            ```

        -   实例ID形式添加数据源

            在数据库名后拼接`?characterEncoding=utf8&com.mysql.jdbc.faultInjection.serverCharsetIndex=45`。

            ![实例ID](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/156698844654661_zh-CN.png)

    -   空字段引起的脏数据。

        ``` {#codeblock_o9d_cz6_yr4}
        {“exception”:“Column ‘xxx_id’ cannot be null”,“record”:[{“byteSize”:0,“index”:0,“type”:“LONG”},{“byteSize”:8,“index”:1,“rawData”:-1,“type”:“LONG”},{“byteSize”:8,“index”:2,“rawData”:641,“type”:“LONG”}
        ```

        经DataX智能分析，该任务最可能的错误原因如下所示：

        ``` {#codeblock_4xe_amp_j51}
        com.alibaba.datax.common.exception.DataXException: Code:[Framework-14]
        ```

        错误解读：

        DataX传输脏数据超过用户预期，该错误通常是由于源端数据存在较多业务脏数据导致。请仔细检查DataX汇报的脏数据日志信息，或者您可以适当调大脏数据阈值。

        脏数据条数检查不通过，限制是1条，但实际上捕获了7条。

        排查思路：

        设置Column ‘xxx\_id’ cannot be null字段不能为空，但数据中用空数据导致脏数据，修改其数据或对字段进行修改。

    -   Data too long for column ‘flash’字段设置太小引起的脏数据。

        ``` {#codeblock_5s7_2j5_4jb}
        2017-01-02 17:01:19.308 [16963484-0-0-writer] ERROR StdoutPluginCollector 
        脏数据：  
        {“exception”:“Data truncation: Data too long for column ‘flash’ at row 1”,“record”:[{“byteSize”:8,“index”:0,“rawData”:1,“type”:“LONG”},{“byteSize”:8,“index”:3,“rawData”:2,“type”:“LONG”},{“byteSize”:8,“index”:4,“rawData”:1,“type”:“LONG”},{“byteSize”:8,“index”:5,“rawData”:1,“type”:“LONG”},{“byteSize”:8,“index”:6,“rawData”:1,“type”:“LONG”}
        ```

        排查思路：

        设置Data too long for column ‘flash’字段设置太小，但数据中数据太大导致脏数据，修改其数据或对字段进行修改。

    -   read-only数据库权限设置问题，设置只读权限。

        ``` {#codeblock_htq_d0j_kl6}
        2016-11-02 17:27:38.288 [12354052-0-8-writer] ERROR StdoutPluginCollector 
        脏数据：  
        {“exception”:“The MySQL server is running with the --read-only option so it cannot execute this statement”,“record”:[{“byteSize”:3,“index”:0,“rawData”:201,“type”:“LONG”},{“byteSize”:8,“index”:1,“rawData”:1474603200000,“type”:“DATE”},{“byteSize”:8,“index”:2,“rawData”:“9月23号12点”,“type”:“STRING”},{“byteSize”:5,“index”:3,“rawData”:“12:00”,“type”:“STRING”}
        ```

        排查思路：

        设置read-only模式，同步数据全为脏数据，修改其数据库模式，运行可以写入。

    -   分区错误。

        参数配置为$\[yyyymm\] 报错，日志如下所示：

        ``` {#codeblock_rv6_1ot_irm}
        [2016-09-13 17:00:43]2016-09-13 16:21:35.689 [job-10055875] ERROR Engine
        ```

        经DataX智能分析，该任务最可能的错误原因如下：

        ``` {#codeblock_skr_p2s_s49}
        com.alibaba.datax.common.exception.DataXException: Code:[OdpsWriter-13]
        ```

        错误解读：

        执行MaxCompute SQL时抛出异常，可重试。MaxCompute目的表在运行MaxCompute SQL时抛出异常，请联系MaxCompute管理员处理。SQL内容如下所示：

        ``` {#codeblock_vc6_e9q_ln3}
        alter table db_rich_gift_record add IF NOT EXISTS
              partition(pt=’${thismonth}’);
        ```

        排查思路：

        由于加了单引号，调度参数替换无效，解决方法：’$\{thismonth\}’去掉引号调度参数。

    -   column没有配成数组形式。

        ``` {#codeblock_86t_0na_59j}
        Run  command failed.  
        com.alibaba.cdp.sdk.exception.CDPException: com.alibaba.fastjson.JSONException: syntax error, **expect {,** actual error, pos 0  
        at com.alibaba.cdp.sdk.exception.CDPException.asCDPException(CDPException.java:23)
        ```

        排查思路：

        JSON有问题，如下所示：

        ``` {#codeblock_9qp_uz3_o7h}
        "plugin": “mysql”,** 
        “parameter”: { 
        “datasource”: “xxxxx”, 
        ** “column”: “uid”,** 
        “where”: “”, 
        “splitPk”: “”, 
        “table”: “xxx” 
        } 
        **“column”: “uid”,-----没有配成数组形式**
        ```

    -   JDBC的格式填写错误。

        排查思路：

        JDBC格式填错，正确的格式是：`jdbc:mysql://ServerIP:Port/Database`。

    -   测试连通性失败。

        排查思路：

        -   防火墙对IP和端口账号有没有相关的限制。
        -   安全组的端口开发情况。
    -   日志中报uid\[xxxxxxxx\]问题。

        ``` {#codeblock_m5f_wwp_hhm}
        Run  command failed.  
        com.alibaba.cdp.sdk.exception.CDPException: RequestId[F9FD049B-xxxx-xxxx-xxx-xxxx] Error: CDP server encounter problems, please contact us, reason: 获取实例的网络信息发生异常,请检查RDS购买者id和RDS实例名,uid[xxxxxxxx],instance[rm-bp1cwz5886rmzio92]ServiceUnavailable : The request has failed due to a temporary failure of the server.  
        RequestId : F9FD049B-xxxx-xxxx-xxx-xxxx
        ```

        排查思路：

        通常RDS同步至MaxCompute时，如果报上述错误，您可以直接将RequestId：F9FD049B-xxxx-xxxx-xxx-xxxx复制给RDS人员。

    -   MongoDB中的query参数错误。

        MongoDB同步到MySQL报下面的问题，排查出JSON没有写好，是JSON中的query参数没有配置好。

        ``` {#codeblock_mgd_rnw_j4v}
        Exception in thread “taskGroup-0” com.alibaba.datax.common.exception.DataXException: Code:[Framework-13]
        ```

        错误解读：

        DataX插件运行时出错，具体原因请参见DataX运行结束时的错误诊断信息。

        ``` {#codeblock_pyj_9wa_48m}
        org.bson.json.JsonParseException: Invalid JSON input. Position: 34. Character: ‘.’.
        ```

        排查思路：

        -   错误示例：`“query”:”{‘update_date’:{’$gte’:new Date().valueOf()/1000}}”`，不支持如new Date\(\)的参数。
        -   正确示例：`“query”:”{‘operationTime’{’$gte’:ISODate(’${last_day}T00:00:00.424+0800’)}}”`。
    -   Cannot allocate memory

        ``` {#codeblock_y4r_mc9_crk}
        2017-10-11 20:45:46.544 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] taskId[358] attemptCount[1] is started  
        Java HotSpot™ 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f15ceaeb000, 12288, 0) failed; error=‘**Cannot allocate memory’** (errno=12)
        ```

        排查思路：

        内存不够。如果运行在自己的资源上，需要自行添加内存。如果运行在阿里的资源上，请提交工单进行咨询。

    -   max\_allowed\_packet参数错误。

        错误信息如下所示：

        ``` {#codeblock_htz_p7d_u44}
        Packet for query is too large (70 > -1). You can change this value on the server by setting the max_allowed_packet’ variable. - **com.mysql.jdbc.PacketTooBigException: Packet for query is too large (70 > -1). You can change this value on the server by setting the max_allowed_packet’ variable.**
        ```

        排查思路：

        -   max\_allowed\_packet参数用来控制其通信缓冲区的最大长度。MySQL根据配置文件会限制server接受的数据包大小。有时候大的插入和更新会被max\_allowed\_packet参数限制掉，导致失败。
        -   max\_allowed\_packet参数的设置太大就改小的一点，通常10m=10\_1024\_1024。
    -   HTTP Status 500读取日志失败。

        ``` {#codeblock_ca7_1sm_74q}
        Unexpected Error:  
        Response is com.alibaba.cdp.sdk.util.http.Response@382db087[proxy=HTTP/1.1 500 Internal Server Error [Server: Tengine, Date: Fri, 27 Oct 2017 16:43:34 GMT, Content-Type: text/html;charset=utf-8, Transfer-Encoding: chunked, Connection: close,  
        **HTTP Status 500** - Read timed out**type** Exception report**message**++Read timed out++**description**++The server encountered an internal error that prevented it from fulfilling this request.++**exception**  
        java.net.SocketTimeoutException: Read timed out
        ```

        排查思路：

        调度运行报500的问题，若是运行在默认资源上，读取日志失败，请直接联系技术支持帮您解决。如果运行在您自己的资源上，请重启Alisa即可。

        **说明：** 如果刷新后还是停止状态，您可以重启Alisa命令：切换到admin账号执行`/home/admin/alisatatasknode/target/alisatatasknode/bin/serverct1 restart`。

    -   hbasewriter参数：hbase.zookeeper.quorum配置错误。

        ``` {#codeblock_3oz_mpe_qc7}
        2017-11-08 09:29:28.173 [61401062-0-0-writer] INFO  ZooKeeper - Initiating client connection, connectString=xxx-2:2181,xxx-4:2181,xxx-5:2181,xxxx-3:2181,xxx-6:2181 sessionTimeout=90000 watcher=hconnection-0x528825f50x0, quorum=node-2:2181,node-4:2181,node-5:2181,node-3:2181,node-6:2181, baseZNode=/hbase  
        Nov 08, 2017 9:29:28 AM org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper checkZk  
        WARNING: **Unable to create ZooKeeper Connection**
        ```

        排查思路：

        -   错误示例：“hbase.zookeeper.quorum”:“xxx-2,xxx-4,xxx-5,xxxx-3,xxx-6”
        -   正确示例：“hbase.zookeeper.quorum”:“您的zookeeperIP地址”
    -   没有找到相应的文件。

        经DataX智能分析，该任务最可能的错误原因如下所示：

        ``` {#codeblock_61x_rjv_pfe}
        com.alibaba.datax.common.exception.DataXException: Code:[HdfsReader-08]
        ```

        错误解读：

        您尝试读取的文件目录为空。未能找到需要读取的文件，请确认您的配置项。

        ``` {#codeblock_wr5_lcg_9ht}
        path： /user/hive/warehouse/tmp_test_map/*  
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        ```

        排查思路：

        按照path找到相应的地方，检查对应的文件。如果没有找到文件，则对文件进行处理。

    -   表不存在。

        经DataX智能分析，该任务最可能的错误原因如下所示：

        ``` {#codeblock_b68_8w8_274}
        com.alibaba.datax.common.exception.DataXException: Code:[MYSQLErrCode-04]
        ```

        错误解读：

        表不存在，请检查表名或者联系数据库管理员确认该表是否存在。

        表名为：xxxx。

        执行的SQL为`select * from xxxx where 1=2;`

        错误信息如下所示：

        ``` {#codeblock_509_0ho_ei8}
        Table ‘darkseer-test.xxxx’ doesn’t exist - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table ‘darkseer-test.xxxx’ doesn’t exist
        ```

        排查思路：

        `select * from xxxx where 1=2`判断表xxxx是否存在问题，如果有问题则要对表进行处理。


