# 如何排查数据集成问题 {#concept_bnt_kkb_r2b .concept}

当通过数据集成实现某操作出现问题时，首先要定位问题的相关信息。例如运行在什么资源上，查看数据源的相关信息，查看在哪个Region配置的同步任务等。

## 查看运行资源 {#section_bhk_mhb_r2b .section}

-   运行在阿里的资源上：

    running in Pipeline\[basecommon\_ group\_xxxxxxxxx\]

-   运行在自己的资源上：

    running in Pipeline\[basecommon\_xxxxxxxxx\]


## 查看数据源信息 {#section_v3x_shb_r2b .section}

需要查看的数据源的相关信息如下：

1.  确认是什么数据源之间的同步。
2.  确认是什么环境的数据源。

    阿里云数据库、有公网IP、无公网IP、VPC网络环境的数据源（RDS或其他数据源）、金融云环境（VPC环境，经典网络）。

3.  确认数据源测试连通性是否成功。

    请参见[配置数据源](intl.zh-CN/使用指南/数据集成/数据源配置/支持的数据源.md#)文档，检查其数据源相关信息是否填错。通常填错的情况如下：

    -   多个数据源库填错。
    -   填写的信息中加了空格或特殊字符。
    -   不支持测试连通性的问题（无公网IP，除RDS的VPC环境的数据源）。

## 确认配置任务的Region {#section_dfl_snb_r2b .section}

进入DataWorks的管理控制台，可以看到相关的Region，如华东2、华南1、香港、亚太东南亚1、欧洲中部1、亚太东南2等，通常默认是华东2。

**说明：** 购买MaxCompute后，才能查看到相应的Region。

![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15542704108678_zh-CN.png)

## 界面模式报错，复制排查码 {#section_n3w_ynb_r2b .section}

如果报错，请复制排查码，并提供给处理人员。

![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15542704108679_zh-CN.jpg)

## 解读日志报错 {#section_i2l_g4b_r2b .section}

-   **日志中报SQL语句执行失败（列包含关键字）**

    ```
    2017-05-31 14:15:20.282 [33881049-0-0-reader] ERROR ReaderRunner - Reader runner Received Exceptions:com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-07]
    ```

    **错误解读**：

    读取数据库数据失败，请检查您配置的 column/table/where/querySql 或者向 DBA 寻求帮助。

    执行的SQL如下所示：

    ```
    select **index**,plaid,plarm,fget,fot,havm,coer,ines,oumes from xxx
    ```

    错误信息如下所示：

    ```
    You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near **index**,plaid,plarm,fget,fot,havm,coer,ines,oumes from xxx
    ```

    **排查思路**：

    1.  本地运行SQL语句`select **index**,plaid,plarm,fget,fot,havm,coer,ines,oumes from xxx`，查看其结果，通常也会有相应的报错。
    2.  字段中有关键字index，解决方法加单引号或修改字段。
-   **日志中报SQL语句执行失败（表名带有双引号包单引号）**

    ```
    com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-07]
    ```

    **错误解读**：

    读取数据库数据失败，请检查您配置的column/table/where/querySql或者向DBA寻求帮助。

    执行的SQL如下所示：

    ```
    select /_+read_consistency(weak) query_timeout(100000000)_/ _ from** 'ql_ddddd_[0-31]’ **where 1=2
    ```

    错误信息如下所示：

    ```
    You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘‘ql_live_speaks[0-31]’ where 1=2’ at line 1 - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near **’‘ql_ddddd_[0-31]’ where 1=2’ **
    ```

    **排查思路**：

    配置表名时，双引号包单引号，通常配置常量是双引号包单引号 “table”:\[“‘qlddddd\[0-31\]’”\]直接去掉里面的单引号。

-   **测试数据源连通性失败（Access denied for ...）**

    连接数据库失败，数据库连接串：jdbc:mysql://xx.xx.xx.x:3306/t\_demo，用户名：fn\_test， 异常消息：Access denied for user ‘fn\_test’@’%’ to database ‘t\_demo’ 请确定RDS中已经添加白名单。

    **排查思路**：

    -   Access denied for通常都是填写的信息有问题，请确认您填写的信息。
    -   白名单或者用户的账号有没有对应数据库的权限，RDS管控台可以添加相应的白名单和授权。
-   路由策略有问题，运行的池子oxs和ECS集群。

    ```
    2017-08-08 15:58:55 : Start Job[xxxxxxx], traceId **running in Pipeline[basecommon_group_xxx_cdp_oxs]**ErrorMessage:Code:[DBUtilErrorCode-10]
    ```

    **错误解读**：

    连接数据库失败，请检查您的账号、密码、数据库名称、IP、Port或者向DBA寻求帮助（注意网络环境）。数据库连接失败，因为根据您配置的连接信息，无法从jdbc:oracle:thin:@xxx.xxxxx.x.xx:xxxx:prod 中找到可连接的JDBCUrl. 请检查您的配置并作出修改。

-   **ava.lang.Exception：DataX无法连接对应的数据库**

    **错误解读**：

    出现该错误可能的原因如下：

    -   配置的ip/port/database/jdbc错误，无法连接。
    -   配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
    **排查思路**：

    情况一：

    -   Oracle同步的RDS-PostgreSQL直接单击**运行**，不能在调度中运行，因为运行的池子不同。
    -   可以在添加RDS的数据源时，改成添加普通JDBC形式的数据源，这样Oracle同步的RDS-PostgreSQL是可以的。
    情况二：

    -   VPC环境的RDS-PostgreSQL不能运行在自定义资源组上，因为VPC环境的RDS有反向代理功能，这样与用户自定义资源组存在网络问题。因此，通常VPC环境的RDS直接运行在DataWorks默认的资源即可。如果默认资源不能满足您的需要，要运行在自己的资源上，可以将VPC环境的RDS作为VPC环境JDBC形式的数据源，购买一个同网段的ECS。
    -   通常VPC环境的RDS映射出的URL为`jdbc:mysql://100.100.70.1:4309/xxx`，100开头的IP是后台映射出来的，如果是一个域名的表现形式则为非VPC环境。
-   **HBase Writer不支持date类型**

    HBase同步到hbase:2017-08-15 11:19:29 : State: 4\(FAIL\) | Total: 0R 0B | Speed: 0R/s 0B/s | Error: 0R 0B | Stage: 0.0% ErrorMessage:Code:\[Hbasewriter-01\]

    **错误解读**：

    您填写的参数值不合法。

    Hbasewriter不支持date类型，目前支持的类型包括string、boolean、short、int、long、float和double。

    **排查思路**：

    -   HBase的writer不支持date类型，所以在writer中不能配置date类型。
    -   直接配置string类型，因为HBase没有数据类型的概念，底层通常是byte数组。
-   **JSON格式配置错误**

    column配置错误

    经DataX智能分析，该任务最可能的错误原因如下：

    ```
    com.alibaba.datax.common.exception.DataXException: Code:[Framework-02]
    ```

    **错误解读**：

    DataX引擎运行过程出错，详情请参见DataX运行结束时的错误诊断信息。

    java.lang.ClassCastException：com.alibaba.fastjson。JSONObject cannot be cast to java.lang.String

    **排查思路**：

    发现其JSON配置有问题。

    ```
    
    writer端： 
    “column”:[ 
    { 
    “name”:“busino”, 
    “type”:“string” 
    } 
    ] 
    正确的写法： 
    “column”:[ 
    { 
    “busino” 
    } 
    ]
    ```

-   **JSON List编写缺少\[\]**

    经DataX智能分析，该任务最可能的错误原因是：

    ```
    com.alibaba.datax.common.exception.DataXException: Code:[Framework-02]
    ```

    **错误解读**：

    DataX引擎运行过程出错，详情请参见DataX运行结束时的错误诊断信息。

    ```
    java.lang.String cannot be cast to java.util.List - java.lang.String cannot be cast to java.util.List  
    at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41)
    ```

    **排查思路**：

    少了\[\]，list型变成其他的形式，找到对应的地方填上\[\]即可解决问题。

-   **权限问题**
    -   **缺少delete权限**

        MaxCompute同步到RDS-MySQL，报错如下：

        ```
        ErrorMessage:Code:[DBUtilErrorCode-07]
        ```

        **错误解读**：

        读取数据库数据失败，请检查您配置的column/table/where/querySql或者向DBA寻求帮助。

        执行的SQL如下所示：

        ```
        delete from fact_xxx_d where sy_date=20170903
        ```

        具体错误信息如下所示：

        ```
        **DELETE command denied** to user ‘xxx_odps’@‘[xx.xxx.xxx.xxx](http://xx.xxx.xxx.xxx)’ for table ‘fact_xxx_d’ - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: DELETE command denied to user ‘xxx_odps’@‘[xx.xxx.xxx.xxx](http://xx.xxx.xxx.xxx)’ for table 'fact_xxx_d’
        ```

        **排查思路**：

        DELETE command denied to没有删除此表的权限，到相应的数据库设置相关表的删除权限。

    -   **缺少drop权限**

        ```
        Code:[DBUtilErrorCode-07]
        ```

        **错误解读**：

        读取数据库数据失败，请检查您配置的column/table/where/querySql或者向DBA寻求帮助。

        执行的SQL为`truncate table be_xx_ch`

        具体错误信息如下所示：

        ```
        **DROP command denied to user** ‘xxx’@‘[xxx.xx.xxx.xxx](http://xxx.xx.xxx.xxx)’ for table ‘be_xx_ch’ - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: DROP command denied to user ‘xxx’@‘[xxx.xx.xxx.xxx](http://xxx.xx.xxx.xxx)’ for table 'be_xx_ch’
        ```

        **排查思路**：

        MySQL Writer配置执行前准备语句truncate删除表中的数据报上面错误，是因为没有drop的权限。

-   **ADS权限问题**

    ```
    2016-11-04 19:49:11.504 [job-12485292] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://100.98.249.103:3306/ads_rdb?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true.  
    2016-11-04 19:49:11.505 [job-12485292] WARN  OriginalConfPretreatmentUtil
    ```

    您的配置文件中的列配置存在一定的风险. 因为您未配置读取数据库表的列，当您的表字段个数、类型有变动时，可能影响任务正确性甚至会运行出错。请检查您的配置并作出修改。

    ```
    2016-11-04 19:49:11.528 [job-12485292] INFO Writer$Job
    ```

    如果是MaxCompute\>ADS的数据同步，需要完成以下两方面的授权。

    -   ADS官方账号至少需要有需要同步的表的describe和select权限，因为ADS系统需要获取MaxCompute需要同步表的结构和数据信息。
    -   您配置的ADS数据源访问账号AK，需要拥有向指定的ADS数据库发起load data的权限，您可以在ADS系统中添加授权。
    ```
    2016-11-04 19:49:11.528 [job-12485292] INFO Writer$Job
    ```

    如果是RDS（或其他非MaxCompute数据源）\>ADS的数据同步，实现逻辑为先将数据装载到MaxCompute临时表，再从MaxCompute临时表同步至ADS，中转MaxCompute项目为cdp\_ads\_project，中转项目账号为cloud-data-pipeline@aliyun-inner.com。

    **权限方面**：

    -   ADS官方账号至少需要有需要同步的表（这里指MaxCompute临时表）的describe和select权限，因为ADS系统需要获取MaxCompute需要同步的表的结构和数据信息，此部分部署时已经完成授权。
    -   中转MaxCompute对应的账号cloud-data-pipeline@aliyun-inner.com，要拥有向指定的ADS数据库发起load data的权限，您可以在ADS系统中添加授权。
    **排查思路**：

    出现此问题是因为没有设置load data权限。

    中转项目账号为cloud-data-pipeline@aliyun-inner.com，权限方面：ADS官方账号至少需要拥有需要同步的表（这里指 MaxCompute 临时表）的 describe 和 select 权限，因为ADS系统需要获取MaxCompute需要同步的表的结构和数据信息，此部分部署时已经完成授权，登录ADS管控台给ADS授予load data的权限。

-   **白名单问题**
    -   **没有添加白名单导致测试连通性失败**

        测试连接失败，测试数据源连通性失败：

        ```
        error message: **Timed out after 5000** ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{[address:3717=dds-bp1afbf47fc7e8e41.mongodb.rds.aliyuncs.com](http://address:3717=dds-bp1afbf47fc7e8e41.mongodb.rds.aliyuncs.com), type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {[address:3717=dds-bp1afbf47fc7e8e42.mongodb.rds.aliyuncs.com](http://address:3717=dds-bp1afbf47fc7e8e42.mongodb.rds.aliyuncs.com), type=UNKNOWN, state=CONNECTING,** exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream**}}]
        ```

        **排查思路**

        非VPC环境的MongoDB，添加数据源时报Timed out after 5000，白名单添加有问题。

        **说明：** 如果您使用的是云数据库MongoDB版，MongoDB默认会有root账号。出于安全策略的考虑，数据集成仅支持使用MongoDB数据库对应账号进行连接，您添加使用MongoDB数据源时，也请避免使用root作为访问账号。

    -   **白名单不全**

        ```
        for Code:[DBUtilErrorCode-10]
        ```

        **错误解读**：

        连接数据库失败，请检查您的账号、密码、数据库名称、IP、Port或者向DBA寻求帮助（注意网络环境）。

        错误信息如下所示：

        ```
        java.sql.SQLException: Invalid authorization specification,  message from server: "#**28000ip not in whitelist, client ip is xx.xx.xx.xx".**  
        2017-10-17 11:03:00.673 [job-xxxx] ERROR RetryUtil - Exception when calling callable
        ```

        **排查思路**：

        白名单没有添全，没有将用户自己的资源添加白名单内。

-   **数据源信息填写错误**
    -   **脚本模式配置缺少相应数据源信息（could not be blank）**

        ```
        2017-09-06 12:47:05 [INFO] Success to fetch meta data for table with **projectId [43501]** **项目ID **and instanceId **[mongodb]数据源名.**  
        2017-09-06 12:47:05 [INFO] Data transport tunnel is CDP.  
        2017-09-06 12:47:05 [INFO] Begin to fetch alisa account info for 3DES encrypt with parameter account: [zz_683cdbcefba143b7b709067b362d4385].  
        2017-09-06 12:47:05 [INFO] Begin to fetch alisa account info for 3DES encrypt with parameter account: [zz_683cdbcefba143b7b709067b362d4385].  
        [Error] Exception when running task, message:** Configuration property [accessId]通常是odps数据源要填写的信息 could not be blank!**
        ```

        **排查思路**：

        报错显示没有相应的 accessId 信息，通常出现这种现象是脚本模式，查看用户配置的 json 代码，是否忘记写相应的的 数据源名。

    -   **未填写数据源配置**

        ```
        
        2017-10-10 10:30:08 INFO =================================================== 
        File “/home/admin/synccenter/src/Validate.py”, line 16, in notNone 
        raise Exception(“Configuration property [%s] could not be blank!” % (context)) 
        **Exception: Configuration property [username] could not be blank!**
        ```

        **排查思路**：

        -   根据正常的打出的日志对比：

            ```
            
            [56810] and instanceId(instanceName) [spfee_test_mysql]… 
            2017-10-09 21:09:44 [INFO] Success to fetch meta data for table with projectId [56810] and instanceId [spfee_test_mysql].
            ```

        -   rds-mysql反应出这样的信息说明调数据源失败成功，而且报用户为空，说明没有配置数据源或数据源的位置配置错误，这个用户就将数据源的位置配置错误。
    -   DRDS连接数据超时

        MaxCompute同步数据到DRDS，经常出现下面的错误：

        ```
        [2017-09-11 16:17:01.729 [49892464-0-0-writer] WARN CommonRdbmsWriter$Task
        ```

        回滚此次写入，采用每次写入一行方式提交，原因如下：

        ```
        com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: **Communications link failure  **  
        The last packet successfully received from the server was 529 milliseconds ago.  The last packet sent successfully to the server was** 528 milliseconds ago**.
        ```

        ![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15542704108686_zh-CN.png)

        排查思路：

        datax客户端的超时，在添加DRDS数据源的时候可以加上`?useUnicode=true&characterEncoding=utf-8&socketTimeout=3600000`超时参数

        示例如下：

        ```
        jdbc:mysql://10.183.80.46:3307/ae_coupon?useUnicode=true&characterEncoding=utf-8&socketTimeout=3600000
        ```

    -   系统内部问题

        ![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15542704108687_zh-CN.png)

        排查思路：

        通常是在开发环境将JSON格式改错了然后直接保存，保存后通常会报系统内部问题。界面显示为空白，碰到这样的问题，直接将您的项目名和节点名称提供给技术支持在后台进行处理。

-   **脏数据**
    -   **脏数据（String\[“”\]不能转为Long）**

        ```
        2017-09-21 16:25:46.125 [51659198-0-26-writer] ERROR WriterRunner - Writer Runner Received Exceptions:  
        com.alibaba.datax.common.exception.DataXException: Code:[Common-01]
        ```

        **错误解读**：

        同步数据出现业务脏数据情况，数据类型转换错误。String\[“”\]不能转为Long。

        **排查思路**：

        String\[“”\]不能转为Long：两张表格中的建表语句一样，报上述错误是因为字段类型中的空字段不能转换成Long类型，直接配置成String类型。

    -   **脏数据（Out of range value）**

        ```
        2017-11-07 13:58:33.897 [503-0-0-writer] ERROR StdoutPluginCollector 
        脏数据： 
        {“exception”:“Data truncation: Out of range value for column ‘id’ at row 1”,“record”:[{“byteSize”:2,“index”:0,“rawData”:-3,“type”:“LONG”},{“byteSize”:2,“index”:1,“rawData”:-2,“type”:“LONG”},{“byteSize”:2,“index”:2,“rawData”:“其他”,“type”:“STRING”},{“byteSize”:2,“index”:3,“rawData”:“其他”,“type”:“STRING”}],“type”:“writer”}
        ```

        **排查思路**：

        mysql2mysql，源端设置的是smallint\(5\)，目标端是int\(11\) unsigned，因为smallint\(5\)范围有负数，unsigned不允许有负数，所以产生脏数据。

    -   **脏数据（存储emoji）**

        数据表配置成了可以存储emoji的，同步时报脏数据。

        **排查思路**：

        数据集成默认支持的是utf8，所以添加JDBC格式的数据源时，需要修改utf8mb4的设置，例如：jdbc:mysql://xxx.x.x.x:3306/database?characterEncoding=utf8&com.mysql.jdbc.faultInjection.serverCharsetIndex=45，这样在数据源设置表情符可以同步成功。

    -   **空字段引起的脏数据**

        ```
        {“exception”:“Column ‘xxx_id’ cannot be null”,“record”:[{“byteSize”:0,“index”:0,“type”:“LONG”},{“byteSize”:8,“index”:1,“rawData”:-1,“type”:“LONG”},{“byteSize”:8,“index”:2,“rawData”:641,“type”:“LONG”}
        ```

        经DataX智能分析，该任务最可能的错误原因如下所示：

        ```
        com.alibaba.datax.common.exception.DataXException: Code:[Framework-14]
        ```

        **错误解读**：

        DataX传输脏数据超过用户预期，该错误通常是由于源端数据存在较多业务脏数据导致，请仔细检查DataX汇报的脏数据日志信息，或者您可以适当调大脏数据阈值。

        脏数据条数检查不通过，限制是1条，但实际上捕获了7条。

        **排查思路**：

        设置Column ‘xxx\_id’ cannot be null字段不能为空，但数据中用空数据导致脏数据，修改其数据或对字段进行修改。

    -   **Data too long for column ‘flash’字段设置太小引起的脏数据**

        ```
        2017-01-02 17:01:19.308 [16963484-0-0-writer] ERROR StdoutPluginCollector 
        脏数据：  
        {“exception”:“Data truncation: Data too long for column ‘flash’ at row 1”,“record”:[{“byteSize”:8,“index”:0,“rawData”:1,“type”:“LONG”},{“byteSize”:8,“index”:3,“rawData”:2,“type”:“LONG”},{“byteSize”:8,“index”:4,“rawData”:1,“type”:“LONG”},{“byteSize”:8,“index”:5,“rawData”:1,“type”:“LONG”},{“byteSize”:8,“index”:6,“rawData”:1,“type”:“LONG”}
        ```

        **排查思路**：

        设置Data too long for column ‘flash’字段设置太小，但数据中数据太大导致脏数据，修改其数据或对字段进行修改。

    -   **read-only数据库权限设置问题，设置只读权限。**

        ```
        2016-11-02 17:27:38.288 [12354052-0-8-writer] ERROR StdoutPluginCollector 
        脏数据：  
        {“exception”:“The MySQL server is running with the --read-only option so it cannot execute this statement”,“record”:[{“byteSize”:3,“index”:0,“rawData”:201,“type”:“LONG”},{“byteSize”:8,“index”:1,“rawData”:1474603200000,“type”:“DATE”},{“byteSize”:8,“index”:2,“rawData”:“9月23号12点”,“type”:“STRING”},{“byteSize”:5,“index”:3,“rawData”:“12:00”,“type”:“STRING”}
        ```

        **排查思路**：

        设置read-only模式，同步数据全为脏数据，修改其数据库模式，运行可以写入。

    -   **分区错误**

        参数配置为$\[yyyymm\] 报错，日志如下所示：

        ```
        [2016-09-13 17:00:43]2016-09-13 16:21:35.689 [job-10055875] ERROR Engine
        ```

        经DataX智能分析，该任务最可能的错误原因如下：

        ```
        com.alibaba.datax.common.exception.DataXException: Code:[OdpsWriter-13]
        ```

        **错误解读**：

        执行MaxCompute SQL时抛出异常，可重试。MaxCompute目的表在运行MaxCompute SQL时抛出异常，请联系MaxCompute管理员处理。SQL内容如下所示：

        ```
        alter table db_rich_gift_record add IF NOT EXISTS
              partition(pt=’${thismonth}’);
        ```

        **排查思路**：

        由于加了单引号，调度参数替换无效，解决方法：’$\{thismonth\}’去掉引号调度参数。

    -   **column没有配成数组形式**

        ```
        Run  command failed.  
        com.alibaba.cdp.sdk.exception.CDPException: com.alibaba.fastjson.JSONException: syntax error, **expect {,** actual error, pos 0  
        at com.alibaba.cdp.sdk.exception.CDPException.asCDPException(CDPException.java:23)
        ```

        **排查思路**：

        JSON有问题，如下所示：

        ```
        
        "plugin": “mysql”,** 
        “parameter”: { 
        “datasource”: “xxxxx”, 
        ** “column”: “uid”,** 
        “where”: “”, 
        “splitPk”: “”, 
        “table”: “xxx” 
        } 
        **“column”: “uid”,-----没有配成数组形式**
        ```

    -   **JDBC的格式填错**

        ![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15542704108688_zh-CN.png)

        **排查思路**：

        JDBC格式填错，正确的格式是：jdbc:mysql://ServerIP:Port/Database。

    -   **测试连通性失败**

        ![](http://static-aliyun-doc.oss-cn-hangzhou.aliyuncs.com/assets/img/16281/15542704108692_zh-CN.png)

        排查思路：

        -   防火墙对这个 IP 和端口账号有没有相关的限制。
        -   安全组的端口开发情况。
    -   **日志中报uid\[xxxxxxxx\]问题**

        ```
        Run  command failed.  
        com.alibaba.cdp.sdk.exception.CDPException: RequestId[F9FD049B-xxxx-xxxx-xxx-xxxx] Error: CDP server encounter problems, please contact us, reason: 获取实例的网络信息发生异常,请检查RDS购买者id和RDS实例名,uid[xxxxxxxx],instance[rm-bp1cwz5886rmzio92]ServiceUnavailable : The request has failed due to a temporary failure of the server.  
        RequestId : F9FD049B-xxxx-xxxx-xxx-xxxx
        ```

        **排查思路**：

        通常RDS同步到MaxCompute时若报上述错误，您可直接将RequestId：F9FD049B-xxxx-xxxx-xxx-xxxx复制给RDS同学。

    -   **MongoDB中的query参数错误**

        MongoDB同步到MySQL报下面的问题，排查出JSON没有写好，是JSON中的query参数没有配置好。

        ```
        Exception in thread “taskGroup-0” com.alibaba.datax.common.exception.DataXException: Code:[Framework-13]
        ```

        **错误解读**：

        DataX插件运行时出错，具体原因请参见DataX运行结束时的错误诊断信息。

        ```
        org.bson.json.JsonParseException: Invalid JSON input. Position: 34. Character: ‘.’.
        ```

        **排查思路**：

        -   错误示例：“query”:”\{‘update\_date’:\{’$gte’:new Date\(\).valueOf\(\)/1000\}\}”，不支持 new Date\(\)这样的参数。
        -   正确示例：“query”:”\{‘operationTime’\{’$gte’:ISODate\(’$\{last\_day\}T00:00:00.424+0800’\)\}\}”
    -   **Cannot allocate memory**

        ```
        2017-10-11 20:45:46.544 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] taskId[358] attemptCount[1] is started  
        Java HotSpot™ 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f15ceaeb000, 12288, 0) failed; error=‘**Cannot allocate memory’** (errno=12)
        ```

        **排查思路**：

        内存不够，如果是用户的资源让用户加内存，如果是运行在阿里的资源上直接联系技术支持。

    -   **max\_allowed\_packet参数错误**

        错误信息如下所示：

        ```
        Packet for query is too large (70 > -1). You can change this value on the server by setting the max_allowed_packet’ variable. - **com.mysql.jdbc.PacketTooBigException: Packet for query is too large (70 > -1). You can change this value on the server by setting the max_allowed_packet’ variable.**
        ```

        **排查思路**：

        -   max\_allowed\_packet参数用来控制其通信缓冲区的最大长度。MySQL根据配置文件会限制server接受的数据包大小。有时候大的插入和更新会被max\_allowed\_packet参数限制掉，导致失败。
        -   max\_allowed\_packet参数的设置太大就改小的一点，通常10m=10\_1024\_1024。
    -   **HTTP Status 500读取日志失败**

        ```
        Unexpected Error:  
        Response is com.alibaba.cdp.sdk.util.http.Response@382db087[proxy=HTTP/1.1 500 Internal Server Error [Server: Tengine, Date: Fri, 27 Oct 2017 16:43:34 GMT, Content-Type: text/html;charset=utf-8, Transfer-Encoding: chunked, Connection: close,  
        **HTTP Status 500** - Read timed out**type** Exception report**message**++Read timed out++**description**++The server encountered an internal error that prevented it from fulfilling this request.++**exception**  
        java.net.SocketTimeoutException: Read timed out
        ```

        **排查思路**：

        调度运行报500的问题，若是运行在默认资源上，读取日志失败，请直接联系技术支持帮您解决。如果运行在您自己的资源上，请重启Alisa即可。

        **说明：** 如果刷新后还是停止状态，您可以重启Alisa命令：切换到admin账号执行`/home/admin/alisatatasknode/target/alisatatasknode/bin/serverct1 restart`。

    -   **hbasewriter参数：hbase.zookeeper.quorum配置错误**

        ```
        2017-11-08 09:29:28.173 [61401062-0-0-writer] INFO  ZooKeeper - Initiating client connection, connectString=xxx-2:2181,xxx-4:2181,xxx-5:2181,xxxx-3:2181,xxx-6:2181 sessionTimeout=90000 watcher=hconnection-0x528825f50x0, quorum=node-2:2181,node-4:2181,node-5:2181,node-3:2181,node-6:2181, baseZNode=/hbase  
        Nov 08, 2017 9:29:28 AM org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper checkZk  
        WARNING: **Unable to create ZooKeeper Connection**
        ```

        **排查思路**：

        -   错误示例：“hbase.zookeeper.quorum”:“xxx-2,xxx-4,xxx-5,xxxx-3,xxx-6”
        -   正确示例：“hbase.zookeeper.quorum”:“您的zookeeperIP地址”
    -   **没有找到相应的文件**

        经DataX智能分析，该任务最可能的错误原因如下所示：

        ```
        com.alibaba.datax.common.exception.DataXException: Code:[HdfsReader-08]
        ```

        **错误解读**：

        您尝试读取的文件目录为空。未能找到需要读取的文件，请确认您的配置项。

        ```
        path： /user/hive/warehouse/tmp_test_map/*  
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        ```

        **排查思路**：

        按照path找到相应的地方，检查对应的文件，如果没有找到文件，就对文件进行处理。

    -   **表不存在**

        经DataX智能分析，该任务最可能的错误原因如下所示：

        ```
        com.alibaba.datax.common.exception.DataXException: Code:[MYSQLErrCode-04]
        ```

        **错误解读**：

        表不存在，请检查表名或者联系DBA确认该表是否存在。

        表名为：xxxx。

        执行的SQL为`select * from xxxx where 1=2;`

        错误信息如下所示：

        ```
        Table ‘darkseer-test.xxxx’ doesn’t exist - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table ‘darkseer-test.xxxx’ doesn’t exist
        ```

        **排查思路**：

        select \* from xxxx where 1=2判断表xxxx是否存在问题，如果有问题则要对表进行处理。


